### ISSUE TITLE
JUSTIN: Quiz Categories & Difficulty Levels

### ISSUE THREAD

**Issue by aakrohra** [Aref-Mal/Quiz90#3]
- [ ] Big John wants to browse through/choose questions by category and difficulty level as a guest user. 
- [ ] He plays a sports-based 10-question quiz, on hard difficulty.

**Comment by Aref-Mal** [comment]
This is the same as the TEAMSTORY issue so I will close it and we can discuss the roles that (whos doing what) after implementing the Quiz Generation / Playthrough (team story).
